notifications:
  irc: "chat.freenode.net#meta-toolkit"

language: cpp

sudo: false

os:
  - linux
  - osx

compiler:
    - clang
    - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-4.8
      - libicu-dev
      - llvm-3.6-dev
      - clang-3.6

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then source travis/install_linux.sh; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source travis/install_osx.sh; fi

before_script:
  - mkdir build
  - cd build
  - cp ../config.toml ./

script:
  - ../travis/cmake.sh Debug && make && make clean
  - rm -rf CMake* && ../travis/cmake.sh Release && make && ctest --output-on-failure
